/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e4e1e7",
        "error": "#ffb4ab",
        "on-surface-variant": "#c7c4d7",
        "on-secondary": "#002e6a",
        "on-primary-fixed": "#07006c",
        "outline-variant": "#464554",
        "surface-container-high": "#2a292e",
        "on-tertiary": "#003824",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#494bd6",
        "primary-container": "#8083ff",
        "surface-dim": "#131317",
        "surface-container-highest": "#353439",
        "surface-container": "#1f1f23",
        "primary-fixed": "#e1e0ff",
        "error-container": "#93000a",
        "on-background": "#e4e1e7",
        "outline": "#908fa0",
        "surface-variant": "#353439",
        "primary": "#c0c1ff",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-low": "#1b1b1f",
        "surface": "#131317",
        "tertiary-container": "#00885d",
        "on-secondary-fixed": "#001a42",
        "surface-container-lowest": "#0e0e12",
        "surface-tint": "#c0c1ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#e6ecff",
        "primary-fixed-dim": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-surface": "#e4e1e7",
        "on-tertiary-fixed": "#002113",
        "secondary-container": "#0566d9",
        "background": "#131317",
        "on-tertiary-container": "#000703",
        "surface-bright": "#39393d",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary": "#4edea3",
        "secondary-fixed": "#d8e2ff",
        "on-primary-container": "#0d0096",
        "secondary": "#adc6ff",
        "inverse-on-surface": "#303034",
        "on-secondary-fixed-variant": "#004395",
        "on-primary": "#1000a9"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "gutter-lg": "2rem",
        "space-xs": "0.25rem",
        "margin-sm": "1rem",
        "space-xl": "2.5rem",
        "margin": "2rem",
        "space-sm": "0.5rem",
        "margin-lg": "3rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        label: ["'Space Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Space Grotesk'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Space Grotesk'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Space Grotesk'", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
};
